#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://github.com/abel-udoh permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
